export const ActionType = {
  MAKE_REQUEST: "MAKE_REQUEST",
  FAIL_REQUEST: "FAIL_REQUEST",
  GET_USER_LIST: "GET_USER_LIST",
  GET_USER: "GET_USER",
  GET_DATA: "GET_DATA",
  DELETE_USER: "DELETE_USER",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  GET_USER_OBJ: "GET_USER_OBJ",
};
